# https://jekyllrb.com/docs/configuration/

# site-wide variables
title: ทุนการศึกษาเพื่อน้อง TEF-Net # title of site, used in tab name and elsewhere
email: TEFNetinfo@gmail.com # default email
# google: Jane Smith # default name to search on Google Scholar
# github: fakelab # default GitHub user/org, without the @
twitter: faketwitterhandle # default Twitter handle, without the @
instagram: fakeinstagramhandle # default Instagram handle, without the @
youtube: fakeyoutubechannel # default YouTube channel handle
facebook: TEFNetinfo

# base directory where site is hosted
# set to "" if hosting at a custom domain, eg yoursite.com
baseurl: "tef-net.com"

# default front matter parameters for markdown files
# defaults can be overridden on a particular page, eg:
# ---
# description: Description unique to this page
# background: images/different-bg-for-this-page.jpg
# ---
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      description: ทุนการศึกษาเพื่อน้อง Thailand Educational Funding Network ทุนการศึกษาเพื่อน้องๆนักเรียน ที่ขาดแคลนทุนทรัพย์ # description that will show under search engine results
      background: images/IMG_6980.JPG # background image in header and footer
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from
